#!/usr/bin/env bash
#this script will add a http response header string 
new_string="add_header  X-Served-By  $\hostname;\n# First attempt to serve request as file, then"
ssh ubuntu@35.231.236.13 "sudo sed -i \"s/# First attempt to serve request as file, then/${new_string}/\" /etc/nginx/sites-enabled/default && sudo service nginx restart "
ssh ubuntu@35.231.236.13 "cat /etc/nginx/sites-enabled/default" |  ssh ubuntu@35.231.53.147 "sudo apt-get update && sudo apt-get -y install nginx && sudo chmod a+rwx /etc/nginx/sites-enabled/default && cat > /etc/nginx/sites-enabled/default && sudo service nginx restart "

