#!/usr/bin/env bash
#this script is installing nginx and configured to listen to port 80 and editing the intex file to return string
sudo apt-get update -y
sudo apt-get install nginx -y
sudo chmod a+rw /var/www/test.html
sudo echo 'Holberton School for the win!' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
