#!/usr/bin/env bash
#Script that will install nginx on a brand new ubuntu machine
ADD301_REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default 
sudo systemctl restart nginx
