#!/usr/bin/env bash
#Script that will install nginx on a brand new ubuntu machine
apt-get -y update
apt-get -y install nginx
new_string="server_name _;\nlocation \/redirect_me {\nreturn 301 'https:\/\/www.youtube.com\/watch?v=lTRiuFIWV54';\n}\n"
sudo sed -i "s/server_name _;/${new_string}/" /etc/nginx/sites-enabled/default
sudo echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
